# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwhFJsDy80ei-uZKD0fzDA-HcnePVheY
"""


"""
Experimento:

1 Crear 5 transacciones de datos (pueden ser transacciones simuladas).
2 Construir el árbol y mostrar la raíz.
3 Modificar una transacción y demostrar que la raíz cambia.
4 Generar una prueba de inclusión para la transacción 3 y verificar que es válida.
5 verificar con un dato incorrecto → debe fallar.
"""

from merkletree import MerkleTree


def main():

    # 1. Crear 5 transacciones de datos (pueden ser transacciones simuladas).
    # Crear 5 transacciones simuladas

    transactions = [
        "Alice -> Bob: 10 BTC",
        "Bob -> Carlos: 5 BTC",
        "Carlos -> Diana: 2 BTC",
        "Diana -> Elena: 7 BTC",
        "Elena -> Alice: 3 BTC",
    ]

    print("=" * 70)
    print("ÁRBOL DE MERKLE")
    print("=" * 70)

    print("\nTransacciones originales:")
    for i, tx in enumerate(transactions, start=1):
        print(f"TX{i}: {tx}")


    # 2. Construir árbol

    tree = MerkleTree(transactions)

    print("\n" + "-" * 70)
    print("MERKLE ROOT ORIGINAL")
    print("-" * 70)
    print(tree.root())


    #  Mostrar árbol

    print("\n" + "-" * 70)
    print("ÁRBOL DE MERKLE")
    print("-" * 70)
    print(tree.render_ascii())


    # 3. Modificar una transacción

    modified_transactions = transactions.copy()

    modified_transactions[1] = "Bob -> Carlos: 500 BTC"

    modified_tree = MerkleTree(modified_transactions)

    print("\n" + "-" * 70)
    print("CAMBIO DE UNA TRANSACCIÓN")
    print("-" * 70)

    print(f"TX2 original:  {transactions[1]}")
    print(f"TX2 modificada: {modified_transactions[1]}")

    print("\nRoot original:")
    print(tree.root())

    print("\nRoot después de modificar TX2:")
    print(modified_tree.root())

    print("\n¿La raíz cambió?")
    print(tree.root() != modified_tree.root())


    # 4. Generar prueba de inclusión para TX3

    print("\n" + "-" * 70)
    print("PRUEBA DE INCLUSIÓN PARA TX3")
    print("-" * 70)

    tx3 = transactions[2]

    proof = tree.get_proof(2)

    print(f"Transacción: {tx3}")
    print("\nPrueba de inclusión:")

    for i, step in enumerate(proof, start=1):
        print(f"Paso {i}:")
        print(f"  Hermano: {step.sibling_hash}")
        print(f"  Lado:    {step.side}")


    #  Verificar prueba válida

    valid = MerkleTree.verify_proof(
        tx3,
        proof,
        tree.root()
    )

    print("\n¿La prueba es válida?")
    print(valid)


    # 5. Verificar con un dato incorrecto → debe fallar.

    incorrect_data = "Carlos -> Diana: 999 BTC"

    invalid = MerkleTree.verify_proof(
        incorrect_data,
        proof,
        tree.root()
    )

    print("\n" + "-" * 70)
    print("PRUEBA CON DATO INCORRECTO")
    print("-" * 70)

    print(f"Dato incorrecto: {incorrect_data}")

    print("\n¿La prueba es válida?")
    print(invalid)


if __name__ == "__main__":
    main()