# -*- coding: utf-8 -*-
"""MerkleTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwhFJsDy80ei-uZKD0fzDA-HcnePVheY
"""


"""
Laboratorio 2,

Implementar un Árbol de Merkle con las siguientes especificaciones:

* Cada hoja contiene el hash SHA-256 de un bloque de datos.
* Cada nodo interno contiene el hash SHA-256 de la concatenación de sus dos hijos.
* Si el número de hojas o ramas es impar, la última se duplica.
* La raíz (Merkle Root) es el hash que representa todo el conjunto.
"""


import hashlib
from dataclasses import dataclass
from typing import List, Tuple


def sha256_hex(data: bytes) -> str:
    """Devuelve el hash SHA-256 de 'data' en formato hexadecimal."""
    return hashlib.sha256(data).hexdigest()


@dataclass
class ProofStep:
    """Un paso de la prueba de inclusión: el hash hermano y de qué lado va."""
    sibling_hash: str
    side: str  # 'left' o 'right' -> lado en el que va el hermano respecto al hash actual


class MerkleTree:
    def __init__(self, transactions: List[str]):
        if not transactions:
            raise ValueError("Se necesita al menos una transacción para construir el árbol")
        self.transactions: List[str] = list(transactions)
        # self.levels[0] = hojas (ya con padding aplicado si corresponde)
        # self.levels[-1] = [root]
        self.levels: List[List[str]] = []
        self._build()


    # Construcción

    def _hash_leaf(self, tx: str) -> str:
        return sha256_hex(tx.encode("utf-8"))

    def _hash_pair(self, left: str, right: str) -> str:
        return sha256_hex((left + right).encode("utf-8"))

    def _build(self) -> None:
        current = [self._hash_leaf(tx) for tx in self.transactions]
        self.levels = [current]

        while len(current) > 1:
            # Duplicar el último si el nivel es impar
            if len(current) % 2 == 1:
                current = current + [current[-1]]
                self.levels[-1] = current  # guardamos el nivel ya "paddeado"

            next_level = [
                self._hash_pair(current[i], current[i + 1])
                for i in range(0, len(current), 2)
            ]
            self.levels.append(next_level)
            current = next_level


    def root(self) -> str:
        return self.levels[-1][0]


    def height(self) -> int:
        return len(self.levels)


    # Prueba de inclusión (Merkle Proof)

    def get_proof(self, index: int) -> List[ProofStep]:
        """
        Genera la prueba de inclusión para la transacción en la posición 'index'
        (0-based, sobre self.transactions original).
        """
        if index < 0 or index >= len(self.transactions):
            raise IndexError("Índice de transacción fuera de rango")

        proof: List[ProofStep] = []
        idx = index

        # Recorremos todos los niveles menos la raíz
        for level in self.levels[:-1]:
            is_right_node = idx % 2 == 1
            sibling_idx = idx - 1 if is_right_node else idx + 1
            sibling_hash = level[sibling_idx]
            side = "left" if is_right_node else "right"
            proof.append(ProofStep(sibling_hash=sibling_hash, side=side))
            idx //= 2

        return proof


    # Verificación


    def verify_proof(data: str, proof: List[ProofStep], root: str) -> bool:
        """
        Reconstruye el camino desde 'data' (el dato original, tal como se
        insertó) usando la prueba 'proof', y compara el resultado con 'root'.
        """
        computed = sha256_hex(data.encode("utf-8"))
        for step in proof:
            if step.side == "left":
                computed = sha256_hex((step.sibling_hash + computed).encode("utf-8"))
            else:
                computed = sha256_hex((computed + step.sibling_hash).encode("utf-8"))
        return computed == root


    # Visualización

    def render_ascii(self, short: int = 8) -> str:
        """Devuelve una representación ASCII del árbol, nivel por nivel (raíz arriba)."""
        lines = []
        total_levels = len(self.levels)
        for depth in range(total_levels - 1, -1, -1):
            level = self.levels[depth]
            label = "ROOT" if depth == total_levels - 1 else f"NIVEL {depth}"
            hashes = "  ".join(h[:short] for h in level)
            lines.append(f"{label:>8}: {hashes}")
        return "\n".join(lines)


